name: Scheduled Release Workflow For Toolchain

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python (for jq and other tools)
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          jq \
          curl \
          bc \
          binutils-dev \
          bison \
          build-essential \
          ca-certificates \
          ccache \
          clang \
          cmake \
          file \
          flex \
          git \
          libelf-dev \
          libssl-dev \
          libstdc++-$(apt list libstdc++6 2>/dev/null | grep -Eos '[0-9]+\.[0-9]+\.[0-9]+' | head -1 | cut -d . -f 1)-dev \
          lld \
          make \
          ninja-build \
          python3-dev \
          texinfo \
          u-boot-tools \
          xz-utils \
          zlib1g-dev

    - name: Run release script
      env:
        GH_USER: ${{ secrets.GH_USER }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GH_REL_REPO: ${{ secrets.GH_REL_REPO }}
        GH_BUILD_REPO: ${{ secrets.GH_BUILD_REPO }}
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        TG_TOKEN: ${{ secrets.TG_TOKEN }}
        GH_RUN_ID: ${{ github.run_id }}
      run: |
        # Make sure the script is executable
        chmod +x build.sh
        chmod +x upload.sh
        # Execute the script
        ./build.sh
        ./upload.sh
